# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 18080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn


mybatis-plus  configuration:
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: com/example/mapper/xml/*.xml
  global-config:
    db-config:
      update-strategy: not_null


# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: dev
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  mail:
    host: smtp.163.com
    port: 465
    username: a1152581244@163.com
    password: YAihWSt7zX3KbKUj
    protocol: smtps
    properties.mail.smtp.auth: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: UTF-8
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  transaction:
    default-timeout: 15  # 设置默认事务超时15秒

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.ruoyi.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*


shop:
  name: ByteChannel

# XXL-JOB 分布式定时任务配置
xxl:
  job:
    # 执行器开关
    enabled: true
    # 调度中心部署根地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
    admin:
      addresses: http://127.0.0.1:28080/xxl-job-admin
    # 执行器通讯TOKEN [选填]：非空时启用；
    accessToken: 6dxNwQtfuGSarWxB
    executor:
      # 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      appname: ruoyi-system
      # 执行器注册 [选填]：优先使用该配置作为注册地址，为空时使用内嵌服务 "IP:PORT" 作为注册地址。从而更灵活的支持容器类型执行器动态IP和动态映射端口问题。
      address:
      # 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
      ip: 192.168.1.11
      # 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      port: 9999
      # 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      logpath: /data/applogs/xxl-job/jobhandler
      # 执行器日志文件保存天数 [选填] ：过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
      logretentiondays: 30

# 支付平台配置
pay:
  platform:
    # 支付平台域名
#    base-url: https://xnoo.cn/
#    pid: 1901
#    merchant-private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC6xnKRBplIA0EI7HtQZvrsnYd460Xtsmi8wjuVcc4u+vG9a2r7isrLu0NW2qWN+ST++FV92VWPCMiAea6rDkfB+BUlUVTIMseJFusdQLnaorNUxnzzqM8VVLjbcqSIEPs9cODpr0UCHApxsFdEPlwSCD+UDPGjINYMgsAa0dRCvq8g1RPur3iVQb1c0OEuCs3rx/6xuKjhk5lXKBfGfG2atRAd3YI/aD/hGJF5Ez/dhcKeVraiBpeD+38gIzWXIPzZf5Fp/K7nQt5c9RcKA1sIBj0Qe40t972mAwJw+97kNRXWtsscisIt0cI0CEys7BFf9+lJ453WdDt9YaC0buATAgMBAAECggEAZhb+nELNGc2diLEqHiKL2TWpzPBcwrYYBcTtKJySJJ/J7s1+JowQmRd8kUbl4xphnHRE1osq9wnH/mGElb8yfdWKSWGRQ/RtmINMdCri65yvBRGRTuXgezpZ6KlbQXx2t3ixl0nUIHkPRGEs8gJb9QdJKTWCBrZ2CVSWiJJUwT3kFkpXjREYJ3ZW7YCdQcKmdKRdkRPX8RiPXfi7LGo/s5tBESF/RQkm41cDBLkJRNsvxdnzqZ/xwWBFgp9sNc5eogjhQj8bNYhjgWsU9MqvpSdSkq5goPEb4zOwlECDrnferhwdVSEyIAyeaTyHMvNNFxf+cB9KriWs8iU9E/Li4QKBgQD4xp05V0XGyzVgyRcOdmd6B6MBkDLuP00yYPWMqU+eAEsYQO8yt5QsFT4g4KZBtwqWO2F+dO5ZSrEXrG5SI9Op+A6foY5bod7g0y4sebFnDUcJEQr2qSJJ/+iVVH4mWzbinvKOYFarX+uUw6yW+nHeCai8mNPZ6i/eLlZZIxQqKQKBgQDAMuyIDeHNoLlYgTSfSfDSfQeZ4pSoZ1sqnQJTRxmoWx5BAuOH7TDLvghjj+vMo/gwVpi0fAXaP/cZSsPcicQuKMfOsztjqRJ00FKRxvbj0LuwY4pZQ7BMcPNzeNgNaeFrltKpqq02Xk8nzvwZ+ta0L0vVWNG20gIqkf2bWCA32wKBgCuHPP1KeugEqEtOBB3As+xTJ79fRroPE2fMNUquWULxFDKjMfcyzddExEEmbZC0AUM2EqH4vbeb7Q6SWh8/K4ri31QpBWqdEQ1PhhW8GUFJvnMkq0FraJeAEmcGiKgXb6wJWbF1w9RqjSLTdgBYw9Gw6PhO2UqYwlVi0DL6g025AoGBALOz6Wwcbq+wQxv5UpZMsBpeRKkhLRV37cmeG/p5VAgRiewHI26H20PkXjuY6UPhW8D2drjp7R7vB75iJVciiIcQIiGlezXncxY9YbZjbZv8IkD+EPD9VO1j/nxM1NVV1iqeTkHNDz7yVthFs3knC3BVeHX2Ib7qBJSBA7onX5hZAoGAAO+CmIPV33h4HYOgXb/3wV5jxFq1rFz4FP8CYrmWqeYUAiXvtXsw4O8g4tGTKu/pN3QPDXjKUbIpWV/593oU3W7IcUahFl9VX1eU39cQDaFcMu0dwdbMAxe0Qo/fOy/ezQuQf0gTmy5zwDMIqQAdsfeglMJeg5T2azMgSlKmePc=
#    platform-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn2GWLNHtZVxBz0sqKpHEOuL4deFGAi722xtZeK4X7XdVOykGHAT+xVJlzd8tTUYJENSyBM36Y4hIY0lWzO+/P8C5OSMPdE272JWfYvaaFa4UC6MCYjVwatYwcN1TBhVEg/8vmUXv3r3EGhlMAHTt7dLsTOZ5oEQzNDOhFJsSo4YIPfEJ7AlVbHof22g9ezmhIoS6bTcH2ksa0PK1kskGHN+haNbbhaJJSxUkP35iTy9nW2WSVgO1THTAFqW5MI7XPg2Au+OwPyAitUdL1/iSTtPM1O27fjebcNi+385ebN/j9eNGaUegyp2lACx5qNFhwf+letMwwKTa/mBYno/JuwIDAQAB
    pid: 1054
    merchant-private-key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCqVowvNHMZY4WXWIu84rvTsvktAACG9SPsS0V2kB3THvmqM+JmVn4ppJH0HBvkStNt5k/T2ndMmVNpbnj/6TxL0T+MQWk/VWeHyk8vJz3nbbofVJVU/RDmcBfW1pcVdpV8y+ZJMUcOIsxiMgp4qNGMShE882yNytZGvzPEkfhu1LaopRdQCLxCnUcF7hTC5LrLjT8ADzVtTU9WIYjBv9jbDT1twCVM5pAc2lDm1lZnb9hrU62hlC6Ce5uHM/0SUa7zftHSYITJ5jY1Qzzxf/aDlk7eEE83qDY/dQCE5xeiFsM2WthqcjiU7oCUWyDBZXC1ppp0MubH1AllFyzWQRc/AgMBAAECggEAA/tZ85CKUEGfUdZkDdpPAbfhU0f4uy7n1BI+YXMk/1ZuB6iG1lWXRWnvb4FotYF6R8tmelFVEJlU9dX7RiAxpKQTlDfDOhPJA8ea6kNEkzBhdXIIu5/e0UQ1inQhvAK1o+EwVO2t94qgtHru+7sWiu0AUihulTH0qFq33xR6djzA9DfYGhiIJ4X+bdyEQImzYLmWIDFby7kB3pVc08nl4Pqy4eydhDnmKOYqqhjO3l8cxIjTapFAs5wm7VK25dLqwT+uffQnm1Gl3z8bFbxwNHXvMAM3FgUtM+EW7/bBv27epHWW8F1jNcHYjomCqaxT3casoE2qagWsDTDWfV2JgQKBgQDWJBYbThnn+taUL0kRU9ymfH9PzTXcfS18a/CXcIc0/dquc/5EgqfW3daMUZI6R5ox0nTy8YtLfEAEVNsp1y59uggashds9AvM/56FwMiW8sVqEq+m98k+jb+i0sxj3FSe2EH1JVwRM3gGSsaT/te/zf7n0J3HraXauW8ZD8i97wKBgQDLooDk9SCVcNvC54frMeFTZvS6GN4HNixB8FXNswWP/9uwSrfyByrw7L7+sMJHCh1Qbn58oIyvaa7NF1YdVZINGk9Sl3z31vr2wy6vsneM3f5nehlJzDFPv1yqYvL67RdZ88gcbSLstCs6uYb7LwERePF9VlUrL44WISXKjPuLsQKBgFuE1rHawjWjvZtdTiQKrE22/Y40jOVr1knLs+p1HEPojlJqnmvXTzYEX1Je9ljUCzFp2bOOydJ8CrwPLA+IuIThQd9u55YYAwcc5DoTt2bT4M1BqTJ5yddjK1jCMLopCz1L/Xxw+BUd4xkFUjMkAj8mIeAfB5+0NiLxh2q1lTyfAoGAaZgavp9eBiA/1RG6qXt0HIuG2/mJKLQuvwKhe8kZWVKT2Rbly9trqQMbB3chRzU3fj3N2VJnoY5r1m4DebKlyaWa/HkRlHMmME+GJhWlaKa1BXOLKXl5GKFiq/gjh3rqYPrJCfSN57CFui36kMYPB8BveU8LWxmN1Gvb7OyuhAECgYAcLxdoNaWIfeUVhnYcu/cq91UO892G0SyOT3V293wDeUAZfHOffewcnwMEy7yafejY1VXF/SxslvrU6LXGCAWckctFZj/PqDl8kqI5g51Di8cv1f/BkLCFbrhQPOOFYJiC/7lj18w1g/DsjpVqkXbQUCEgJsqurprEenvQ5yV1lw==
    platform-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtIj8OGRj+BOkTRWwrHd33NXyZNKWjoaffguOR1sl7yhJ198ObCrASLgXDi0UxsGo47EYQw35jOm9QEjL6E0gqUJWs8KXZuNMpqX10/biWDWoCnCr9Mx2+QOCuy3qtqrhjUImnJ8STulP2na3FKnQSWMUbJ/frBHPBf4zVIfmApFM27oNmqB/NXJAcIH+dv3LB16CX8Z/+AgDoRjM6z/AcQ2rcuuOuiQ3p27HvmnSOHZNIQtSE1jeIMS6yd03wQRW/lWziGMQYAof3oYNhm4DUGcZfqpz80dkWJWVdTHjgy/YlpMBdSlAL/P2gP7RS9tGf3aF1yjattUq/a8/Q659awIDAQAB
    base-url: https://api.jianxipay.com
    # 异步通知地址
    notify-url: http://81.71.137.39:18080/pay/notify
    # 同步跳转地址
    return-url: http://localhost:8081/#/payment/
    # 签名类型（V2固定为RSA）
    sign-type: RSA
    # 连接超时时间（毫秒）
    connect-timeout: 5000
    # 读取超时时间（毫秒）
    read-timeout: 10000
    # 微信手续费
    wechat-refound: 0.07
    # 支付宝手续费
    alipay-refound: 0.07
